name: Vigilia de Chronos

on:
  schedule:
    # 11:00 UTC = 08:00 Brasília (Foco: Exercícios)
    # 00:00 UTC = 21:00 Brasília (Foco: Finanças)
    - cron: '0 11,0 * * *'
  workflow_dispatch: # Botão para rodar manualmente

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código
        uses: actions/checkout@v3

      - name: Preparar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Dependências
        run: npm install

      - name: Executar Golem
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: node golem.js